{"name": "test_calcsum[5-5-11]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 11", "trace": "input1 = 5, input2 = 5, output = 11\n\n    @pytest.mark.parametrize(\"input1,input2,output\",\n                             [\n                                 (2,3,5),\n                                 (3,3,6),\n                                 (5,5,11)\n                             ]\n                             )\n    def test_calcsum(input1, input2, output):\n        result = sum(input1,input2)\n>       assert result == output\nE       assert 10 == 11\n\ntest_Pytest_Parametrize.py:16: AssertionError"}, "parameters": [{"name": "input1", "value": "5"}, {"name": "input2", "value": "5"}, {"name": "output", "value": "11"}], "start": 1562592466506, "stop": 1562592466506, "uuid": "daa6a755-113e-4ff3-a110-032b5451a5cc", "historyId": "8e90f9514b17c4eae83ad9cdf1f2ae0d", "fullName": "test_Pytest_Parametrize#test_calcsum[5-5-11]", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_Pytest_Parametrize"}, {"name": "subSuite"}, {"name": "host", "value": "30Q9JR2"}, {"name": "thread", "value": "9972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_Pytest_Parametrize"}]}